### ISSUE TITLE
[bug] Warning not displaying texts

### ISSUE THREAD

**Issue by nicxes** [manups4e/ScaleformUI#112]
Im having issues to create a simple warning, any idea if im doing something wrong?

```
RegisterCommand('warning', function()
    ScaleformUI.Scaleforms.Warning:ShowWarning("This is the title", "This is the subtitle", "This is the prompt.. you have 6 seconds left", "This is the error message, ScaleformUI Ver. 3.0")
end)
```

Result:

![image](https://user-images.githubusercontent.com/8798356/236353165-a5d3b641-6579-4a8c-bca7-93bc010ec19f.png)

**Comment by manups4e** [comment]
Thanks I'll make sure to check it asap

**Comment by manups4e** [comment]
the scaleform is working correctly
![image](https://user-images.githubusercontent.com/4005518/236557013-c18c8105-a052-4c76-b50e-2f78ffea9ec5.png)
you didn't add a parameter at the end... you're missing the warningType parameter
try using 
```
ScaleformUI.Scaleforms.Warning:ShowWarning("This is the title", "This is the subtitle", "This is the prompt.. you have 6 seconds left", "This is the error message, ScaleformUI Ver. 3.0", 0)
```
