### ISSUE TITLE
Error when pressing F7 in example script

### ISSUE THREAD

**Issue by nicxes** [manups4e/ScaleformUI#120]
When I press F7 in the example script, I get an error. I am not sure if this is a common issue or if it's just me. Can someone help me fix this issue?

![image](https://user-images.githubusercontent.com/8798356/236667794-4e09d57b-81c5-48f2-84e1-5a3d569b97af.png)

**Comment by Local9** [comment]
I believe this is one of the few outlying issues I was looking into, when I get a moment I'll have a deeper dive to see whats happening with this.
