### ISSUE TITLE
 [LUA] Crash on high number of UIMenuCheckboxItem

### ISSUE THREAD

**Issue by Torelka** [manups4e/ScaleformUI#121]
When i try to create a high number of UIMenuCheckboxItem fivem crash and the reason is a high time to respond from CitizenCrash

the code generating the element (it's sync generation)

```
function createSpecifi(data, menu)

    for index, value in ipairs(data) do      

        local itemchecked= UIMenuCheckboxItem.New(value.nom, false ,0,"Desactiver le composant",1,117,0,0)

        itemchecked.OnCheckboxChanged=function (menu,item,checked)

            local id=item.Base._itemData.data.id

            if(checked) then

                table.insert(underReplace,id)

            else

                for key, value in ipairs(underReplace) do

                    if(value==id) then

                        table.remove(underReplace,key)

                    end

                end    

            end

        end

        itemchecked:ItemData({data=value})

        menu:AddItem(itemchecked)

    end 

end
```

**Comment by Local9** [comment]
What is a "high number" ?

**Comment by manups4e** [comment]
a workaround for the moment would be making ListItems with a "On/Off" selection.

**Comment by Torelka** [comment]
after some test on my own after 60 elements, the game freeze really hard and crash. The initial amount was 145 elements.

Nice suggestion. i will try this.

**Comment by manups4e** [comment]
Just to update, there has been some development work on changing how menus are handled. Most updates are mentioned on the [Discord](https://discord.gg/fivemscripters) 
and in the Dev branch

**Comment by manups4e** [comment]
Hint on the incoming update :) you can add more than 2000 checkboxes without any lag.

https://github.com/manups4e/ScaleformUI/assets/4005518/52f58e1c-6f99-40d1-9795-f177758de597

**Comment by manups4e** [comment]
already fixed in next major version! https://github.com/manups4e/ScaleformUI/commit/758a0fcf829e756aca616e55849080d9c68b7e07
