### ISSUE TITLE
[LUA] Conflict with Other Menus

### ISSUE THREAD

**Issue by nicxes** [manups4e/ScaleformUI#131]
After updating to the latest version, I have encountered an issue with the menu banner not moving to the right as it used to. The banner remains in its initial left position at all times. Additionally, I suspect this menu is conflicting with other menus in my server. The title of this menu library overlaps with the title of another menu, causing visibility issues with the options. The options are not displayed properly, and it becomes challenging to navigate through them.

Furthermore, when I use the arrow keys on the keyboard to navigate within the menu, the navigation appears to be inverted. For example, when I press the up arrow key, the selection moves downward, and vice versa.

![image](https://github.com/manups4e/ScaleformUI/assets/8798356/fab88f3b-d932-495f-9bc5-cf8ff9d39850)

-----

In version 3.0.0, I have a video demonstrating how it was before. However, I encountered issues with one menu (character customization) where the options were getting duplicated, and some texts were appearing from other menus.

https://cdn.discordapp.com/attachments/982938924496355389/1105963321951273050/2023-05-10_17-57-20.mp4

**Comment by nicxes** [comment]
Thank you for the response!

I appreciate your assistance. In the first screenshot I shared, I was using version 3.0.2. However, due to some issues, I have decided to revert back to version 3.0.0, which seems to have fewer problems.

Regarding the issue I mentioned, here is the code for the character creation and customization: https://gist.github.com/nicxes/f0f5d3b651815ea938c2b6e3e568aa91

If you remove the function 330, you will notice that the next menu experiences some glitches as well.

I hope this additional information helps in further investigating the issue.

**Comment by Local9** [comment]
Ok, so this looks to be round the `FlushAllMenus` method, which taking a quick look at the method it needs to be changed as work was done to `CloseAllMenus` but the same was not done to that method.

@manups4e would you be able to have a quick look? Is it just the indexing that needs updating for Lua/JS handling like in `CloseAllMenus`?

Affects;
- [FlushMenus](https://github.com/manups4e/ScaleformUI/blob/b50cde87238f309f14d7ec1eb778ba41e066f699/ScaleformUI_Lua/src/base/MenuPool.lua#L289)
- [FlushPauseMenus](https://github.com/manups4e/ScaleformUI/blob/b50cde87238f309f14d7ec1eb778ba41e066f699/ScaleformUI_Lua/src/base/MenuPool.lua#L300)
- [FlushAllMenus](https://github.com/manups4e/ScaleformUI/blob/b50cde87238f309f14d7ec1eb778ba41e066f699/ScaleformUI_Lua/src/base/MenuPool.lua#L311)

**Comment by JFCO-Highlander** [comment]
Encountered a similar issue. Here's the reproduction steps:

1. Create a menu
2. Create a submenu within that menu
3. Navigate to the submenu and select an item inside of that. Call pool:CloseAllMenus() or pool:FlushAllMenus() on the selectItem

End result: Overlapping menus. Appears that the submenu doesn't fully close/flush, and will appear when the main menu is reopened.

**Comment by manups4e** [comment]
🤔 i see.. thanks i'll test it asap and let you know! 😄

**Comment by Local9** [comment]
> This can actually be replicated using the example.lua provided.
> 
>     1. Press F5
> 
>     2. Press enter on 'Big Message Example'
> 
>     3. Press G to flush the pool
> 
>     4. Press F5 again, observe overlapped menus

I'm currently unable to replicate with the latest Assets and ScaleformUI files, is this limited to a set version?

**Comment by Local9** [comment]
Just to update, there has been some development work on changing how menus are handled. Most updates are mentioned on the [Discord](https://discord.gg/fivemscripters)

**Comment by manups4e** [comment]
already fixed in next major version! https://github.com/manups4e/ScaleformUI/commit/758a0fcf829e756aca616e55849080d9c68b7e07
