### ISSUE TITLE
[Lua] Top menu title stays after entering submenu

### ISSUE THREAD

**Issue by DatGuy1** [manups4e/ScaleformUI#136]
See https://i.imgur.com/Y7wQ2Jf.mp4 as an example. Using latest release.

Possibly related to #131, unsure.

**Comment by manups4e** [comment]
already fixed in next major version! 😅

**Comment by manups4e** [comment]
https://github.com/manups4e/ScaleformUI/commit/758a0fcf829e756aca616e55849080d9c68b7e07
