### ISSUE TITLE
[LUA] Scrolling through items in a UIMenuListItem causes item text to slowly move up

### ISSUE THREAD

**Issue by Asaayu** [manups4e/ScaleformUI#148]
[Example of the issue](https://i.gyazo.com/6aa33cd55a9c382950a04ad90eb5bc4c.mp4)
Going through the items in a UIMenuListItem causes the text position to slowly increase in height.

**Comment by manups4e** [comment]
fixed https://github.com/manups4e/NativeUI-scaleform_flash/commit/acee00fd8d8fa2c8e68e32209ecdb060ae4ed12c
