### ISSUE TITLE
[LUA] UIMenu processes user inputs while hidden by a warning message

### ISSUE THREAD

**Issue by Asaayu** [manups4e/ScaleformUI#149]
[Example video of the issue](https://i.gyazo.com/a115ce5f3ff6e787eeea539e0fd35455.mp4)

The `UIMenu:Draw` function has handling for if a warning is showing, but the `UIMenu:ProcessControl` function doesn't, so any user inputs pressed while showing a warning get processed by the UIMenu behind the warning.

**Comment by manups4e** [comment]
should be fixed with https://github.com/manups4e/ScaleformUI/commit/3f9e612c2e472646965f554212b786d0ff87b445 and https://github.com/manups4e/ScaleformUI/commit/8e7e1649105c3d791973665664cc1b14358f1e1d

**Comment by Asaayu** [comment]
After testing the issue is no longer present
