### ISSUE TITLE
[LUA] UIMenu instructional buttons disappear after closing ShowWarningWithButtons

### ISSUE THREAD

**Issue by Asaayu** [manups4e/ScaleformUI#154]
[Example video of the issue](https://i.gyazo.com/918062a543979730859ec03d0ec4f6a6.mp4)

If a ShowWarningWithButtons is opened while a UIMenu is showing, the instructional buttons for the UIMenu will not shown to the user after the warning is closed.

Reproduction:
Open a UIMenu with instructional buttons.
Open a warning screen while the menu is open.
Close the warning screen.
The original UIMenu instructional buttons are now missing until the menu is opened again or the user navigates to a child menu

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/4a2db4f53db7f0dca1f031d6c0b8bbc17e026996
