### ISSUE TITLE
[PauseMenu C#] Issue with RightLabel & text visibility issue

### ISSUE THREAD

**Issue by nicxes** [manups4e/ScaleformUI#168]
When I use the following code snippet to prompt the user for an email and then set the RightLabel to the entered email, it doesn't display the expected email string. Instead, it shows some random symbols.

```c#
emailItem.OnActivate += async (item) =>
{
    email = await Utils.Input.Keyboard("Email:", email, true, 20, null, pauseMenu);
    emailItem.RightLabel = email;
};
```

There's another intermittent issue concerning the text color and background color of the menu items. Occasionally, when hovering over a menu item, both the text color and background color turn white, making it impossible to read.

![image](https://github.com/manups4e/ScaleformUI/assets/8798356/af70b916-4fc8-469f-ab6d-b76360136764)

**Comment by manups4e** [comment]
random symbols are because of the maybe selected font 🤔 this is the GTAV_LEADERBOARD font

**Comment by manups4e** [comment]
closed after no further updates.

**Comment by nicxes** [comment]
> random symbols are because of the maybe selected font 🤔 this is the GTAV_LEADERBOARD font

I didn't pick any font on purpose. I'm just using the defaults. And I can't find where to set the font for the RightLabel.

Oh, and sorry for the late reply. Been super busy with work lately.

**Comment by manups4e** [comment]
super weird 🤔 are you using latest assets and latest script?
