### ISSUE TITLE
UIMenuStatsItem Display Issue When Selected

### ISSUE THREAD

**Issue by nicxes** [manups4e/ScaleformUI#172]
When creating a `UIMenuStatsItem`, it functions correctly, but the background looks off when the item is selected.

![image](https://github.com/manups4e/ScaleformUI/assets/8798356/018fd5bf-abf0-4cfc-9125-9fb70fee004f)

**Comment by manups4e** [comment]
nice find!!! i'll check it asap!

**Comment by manups4e** [comment]
![image](https://github.com/manups4e/ScaleformUI/assets/4005518/f6a8fff7-4077-4061-9382-af194f528c81)

to me it's workiong correctly

**Comment by manups4e** [comment]
![image](https://github.com/manups4e/ScaleformUI/assets/4005518/e4dbc4ec-edec-4759-be03-c3bc85b2d6da)
it works with multiple ones too both in lua and c#

**Comment by manups4e** [comment]
Closing for now as i don't see any bug in my test environment.. could be re-opened in future

**Comment by nicxes** [comment]
Using the latest assets (4.2.5 version) fixed this issue.
