### ISSUE TITLE
Proper way to handle menus?

### ISSUE THREAD

**Issue by DatGuy1** [manups4e/ScaleformUI#173]
What's the proper way to handle menus? Recreating them every time they are used? Or toggling menu:Visible(not menu:Visible())?

**Comment by manups4e** [comment]
the "Or" here is unneded..
- my personal approach is to update menus on creation.. my way of making them is basically re-make them everytime they're needed this way data is always updated on menu opening, and after that if i need live updating i simply run a tick on frame to update menu data when needed.
- i use Visible(true) when i want it to be visible and Visible(false) when i want to hide it (without user input) consider that usually the user exits the menu so you don't need to do Visible(false) so.. you have `true`/`false` keywords.. use them ahaha
