### ISSUE TITLE
Menu not opening on latest release (2.3.0)

### ISSUE THREAD

**Issue by ali-exacute** [manups4e/ScaleformUI#19]
Latest release that includes New Lobby Menus, have a very small issue on CreateMenu (as it is older than what it is already inside github (not release)

just wanted to tell you about this, so people dont get confused on using the latest version !

To be exact : 
![Capture](https://user-images.githubusercontent.com/16070339/170649815-26886aeb-91b7-4094-82ed-70b77a06f8a6.PNG)

This part is the issue, as it is trying to add sub1 as a submenu to sub1 again !
_(and sub2 is not even used at all)_

I am not sure what is the intended use but this will fix the error and menu will show up correctly and also will use sub2 aswell

```lua
local sub1 = UIMenu.New("Ciao", "ciao", 50, 50, true, nil, nil, true)
local sub2 = UIMenu.New("Ciao", "ciao", 50, 50, true, nil, nil, true)

exampleMenu:AddSubMenu(sub1, "test", "test")
exampleMenu:AddSubMenu(sub2, "test", "test")
```

**Comment by manups4e** [comment]
yes i noticed that.. it was an old test of mine that i forgot.. i'll update a new release now for lua only :)

**Comment by manups4e** [comment]
https://github.com/manups4e/ScaleformUI/releases/tag/2.3.1
