### ISSUE TITLE
[Lua] PlayerListColumn:Clear() contains a typo causing an error when trying to call the function

### ISSUE THREAD

**Issue by Lxk3y** [manups4e/ScaleformUI#198]
Calling "myMenu.PlayersColumn:Clear()" in a script throws the following error
![image](https://github.com/manups4e/ScaleformUI/assets/47719567/79382ae0-90eb-4e62-9b91-9f276488042d)
This is cause by the following typo
![image](https://github.com/manups4e/ScaleformUI/assets/47719567/e218f2e7-693b-4391-9227-eea72ead52ed)

Simple fix :)

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/42e60c83bb3676c7f4ca886803885daf627e6192
