### ISSUE TITLE
Escape key both close menus and open default pause menu

### ISSUE THREAD

**Issue by ali-exacute** [manups4e/ScaleformUI#20]
I think i am getting a bit annoying with all of my new issues :D 
But i really love this resource

ANYWAY ,

Not sure if this is intended or not but,
when Lobby menu or custom pause menu is opened, if you press backspace or right mouse click , it will close as it should , but whenever you use ESC key , it will both close it and open GTA default pause menu

_it works fine on default menus, but not on lobby and pause menus_

**Comment by manups4e** [comment]
yup i'm still thinking on how to handle this behaviour 🤔 didn't touch anything yet for some reasons 🤔 you can still disable PauseMenu input if you want while opening the menus

**Comment by manups4e** [comment]
also.. if you want check my discord profile and join my server, we have a dedicated scaleform section 😄

**Comment by ali-exacute** [comment]
> also.. if you want check my discord profile and join my discord server, we have a dedicated scaleform channel 😄

i would love to join , but i cant find the invite link anywhere.

**Comment by manups4e** [comment]
you can check my discord profile manups4e#8967

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/0e23e9249bd2bab038ca1733d673b3e2cab93db4
