### ISSUE TITLE
attempt to call a nil value (method 'ToArgb')

### ISSUE THREAD

**Issue by RealMrCactus** [manups4e/ScaleformUI#216]
![image](https://github.com/user-attachments/assets/cc02227a-867c-468c-8322-cf93e8ff439b)

```lua
local menu = UIMenu.New("Echeveria", "Mod Trainer", 10, 10, false, "uh", "fuck", false, 0.1)
local plropt = UIMenuItem.New("Player Options", "Options related to the player", "HUD_COLOUR_PAUSE_BG", "HUD_COLOUR_BLUE", "HUD_COLOUR_BLACK", "HUD_COLOUR_BLACK")

menu:AddItem(plropt)

RegisterCommand("echeveria", function ()
    menu:Visible(true)
end, false)

RegisterKeyMapping("echeveria", "Opens the trainer", "KEYBOARD", "f1")

```

also Please PLEASE PLEASE add value types to the lua examples because where i wrote "uh" and "fuck" i had no idea what i needed to put there

**Comment by manups4e** [comment]
Oh and fuck are custom texture dictionary and custom texture name
Besides that.. toargb is working fine on my end and it applies only on the SColor meta class.. can you provide your code with the error instead of asking for 2 problems mixed?
Value types should also be described in the UIMENU metaclass as you can see here
https://github.com/manups4e/ScaleformUI/blob/c37266507af64cad796bec60f0d408199e89297a/ScaleformUI_Lua/src/Menus/UIMenu/UIMenu.lua#L103

**Comment by RealMrCactus** [comment]
> Oh and fuck are custom texture dictionary and custom texture name Besides that.. toargb is working fine on my end and it applies only on the SColor meta class.. can you provide your code with the error instead of asking for 2 problems mixed? Value types should also be described in the UIMENU metaclass as you can see here
> 
> https://github.com/manups4e/ScaleformUI/blob/c37266507af64cad796bec60f0d408199e89297a/ScaleformUI_Lua/src/Menus/UIMenu/UIMenu.lua#L103
> 
> 
> So please PLEASE PLEASE make sure to read before you ask 😊

I did give you my code

**Comment by manups4e** [comment]
So the ToArgb error appears on loading without you calling it?

**Comment by RealMrCactus** [comment]
> So the ToArgb error appears on loading without you calling it?

I presume the menu creation causes it, it only happens after I attempt to press the bind to open the menu

**Comment by manups4e** [comment]
All right 😊 I'll check it in 10 mins and release a fix asap

**Comment by manups4e** [comment]
can i ask what version are you on? I just tried loading latest released version 
![image](https://github.com/user-attachments/assets/6a06eabc-1669-4857-bac3-f5957b16d087)
and everything looks just fine

**Comment by manups4e** [comment]
ok i found your bug
```lua 
local plropt = UIMenuItem.New("Player Options", "Options related to the player", "HUD_COLOUR_PAUSE_BG", "HUD_COLOUR_BLUE", "HUD_COLOUR_BLACK", "HUD_COLOUR_BLACK")
```
you set the colors as strings.. bad.. colors are not strings but SColor instances
```lua
local scrollingAnimationItem = UIMenuListItem.New("Choose the scrolling animation", animations, exampleMenu:AnimationType(),"~BLIP_BARBER~ ~BLIP_INFO_ICON~ ~BLIP_TANK~ ~BLIP_OFFICE~ ~BLIP_CRIM_DRUGS~ ~BLIP_WAYPOINT~ ~INPUTGROUP_MOVE~~n~You can use Blips and Inputs in description as you prefer!~n~⚠ 🐌 ❤️ 🥺 💪🏻 You can use Emojis too!", SColor.HUD_Freemode_dark, SColor.HUD_Freemode)```

**Comment by RealMrCactus** [comment]
Ah alright I know Lua lmfao just not necessarily FiveMs extension to it

**Comment by RealMrCactus** [comment]
how would i find the texture dicts and what not that are already in the game?

**Comment by manups4e** [comment]
you can find them on google.. an example: https://wiki.rage.mp/index.php?title=Textures 
for the default menu texture use `commonmenu`, `interaction_bgd`

**Comment by RealMrCactus** [comment]
thanks i went down the rabbit hole of scaleforms hoping that might be it lol

**Comment by RealMrCactus** [comment]
how do i use OnItemSelect is it :OnItemSelect(function or .OnItemSelect or something else?

**Comment by manups4e** [comment]
```lua
    bigMessageExampleMenu.OnItemSelect = function(sender, item, index)
        if item == uiItemDisposeBigMessage then
            ScaleformUI.Scaleforms.BigMessageInstance:Dispose()
        end
    end
```
As i already told you.. check the `example.lua` to see every feature of the menus

**Comment by manups4e** [comment]
locking as completed and derailing from an issue to a how-to request
