### ISSUE TITLE
2 or more menus showing up

### ISSUE THREAD

**Issue by RealMrCactus** [manups4e/ScaleformUI#217]
```lua
RegisterCommand("echeveria", function ()
    menu:Visible(true)
end, false)

RegisterKeyMapping("echeveria", "Opens the trainer", "KEYBOARD", "f1")
```

thats how ive been opening it and there is only one `menu` declared

**Comment by manups4e** [comment]
I have no experience on key mappings 🤔 but on ticks this doesn't happen.. might happen that commands are executed twice tho 🤔

**Comment by manups4e** [comment]
Also.. if you restart your script without closing the menu first.. a new instance will open.. that's scaleforns..

**Comment by RealMrCactus** [comment]
i dont think so because if i do the command manually it still happens

**Comment by RealMrCactus** [comment]
> Also.. if you restart your script without closing the menu first.. a new instance will open.. that's scaleforns..

yeah ive been making sure to close it

**Comment by RealMrCactus** [comment]
![image](https://github.com/user-attachments/assets/d0b1184c-21c5-42db-9990-99b9a7521bc5)

**Comment by manups4e** [comment]
the menu opens twice only when visible is set to true 🤔 unless you set Visible(true) twice there's no logic way to make it appear twice i made multiple checks into that.. unless your command is executing twice 🤔

**Comment by RealMrCactus** [comment]
![image](https://github.com/user-attachments/assets/b24869d5-dfa0-4bda-b5a8-b1aba1b8593d)
well im not sure then

**Comment by manups4e** [comment]
I don't use commands so I can't say why this happens.. if you check the example.lua I open the menu via classic IsControlJustPressed native 🤔 and it works flawlessly 🤔 I'll try to investigate but I can't control commands natives

**Comment by RealMrCactus** [comment]
> I don't use commands so I can't say why this happens.. if you check the example.lua I open the menu via classic IsControlJustPressed native 🤔 and it works flawlessly 🤔 I'll try to investigate but I can't control commands natives

i perfer registerKeybind and command so people can set a different keybind if they want

**Comment by manups4e** [comment]
ok so... i've been trying to use this
```
RegisterCommand("echeveria", function ()
    CreateMenu()
end, false)

RegisterKeyMapping("echeveria", "Opens the trainer", "KEYBOARD", "f1")
``` and everything is working fine with example menu

**Comment by Swellington-Soares** [comment]
> ```lua
> RegisterCommand("echeveria", function ()
>     menu:Visible(true)
> end, false)
> 
> RegisterKeyMapping("echeveria", "Opens the trainer", "KEYBOARD", "f1")
> ```
> 
> thats how ive been opening it and there is only one `menu` declared

You can put like this:

`
RegisterCommand('openptfxmenu', function()
    if menu and not MenuHandler:IsAnyMenuOpen() then
        menu:Visible(true)
    end
end)

CreateThread(function()
    CreatePtfxMainMenu() -- create menu 
    RegisterKeyMapping('openptfxmenu', 'Open PTFX Test Menu', 'KEYBOARD', 'F1') -- keybind
end)
`

**Comment by manups4e** [comment]
Thanks for the hint I'll test this in the next days and report 🤔

**Comment by manups4e** [comment]
using the code you provided i did
```lua
RegisterCommand('openptfxmenu', function()
    if exampleMenu and not MenuHandler:IsAnyMenuOpen() then
        exampleMenu:Visible(true)
    end
end)

CreateThread(function()
CreateMenu() -- create menu 
    RegisterKeyMapping('openptfxmenu', 'Open PTFX Test Menu', 'KEYBOARD', 'L') -- keybind
end)
```

and this is the result 

![image](https://github.com/user-attachments/assets/1af268e3-b148-4a5e-a2c8-dfe631e00be2)

i would suggest you to use the correct quake command alike intended for this feature.. so 

![image](https://github.com/user-attachments/assets/589f97ed-2c64-4715-ab04-a0af20fd9b6a)

as you can see i added a minus before the command this is intended for commands that we want to execute once without toggling things.

quick explanation:
![image](https://github.com/user-attachments/assets/35b8dba8-e66e-4381-b832-5ec5d24dd21d)

if you want it to be a +command in this case the command would be 
```lua
RegisterCommand('+openptfxmenu', function()
    if exampleMenu and not MenuHandler:IsAnyMenuOpen() then
        exampleMenu:Visible(true)
    else 
	MenuHandler:CloseAndClearHistory()
    end
end)
```

**Comment by Mathu-lmn** [comment]
What's this issue's status ?

**Comment by RealMrCactus** [comment]
Busy with stuff ATM but will test stuff ASAP

**Comment by manups4e** [comment]
it's been almost 2 months.. closing for now but will keep comments on.
