### ISSUE TITLE
Menus will sometimes pile up on top of each other

### ISSUE THREAD

**Issue by IsmaelJab** [manups4e/ScaleformUI#218]
I've been trying to figure out what exactly causes this, I am 100% sure that I am calling `menu:Visible(true)` once in any case, yet it seems that sometimes the `BreadcrumbsHandler` count sticks to 1 even though no menu is opened, see the following image where I print the result of `MenuHandler:IsAnyMenuOpen()` when the `E` key is pressed inside the marker :

![image](https://github.com/user-attachments/assets/d62bc6fe-44f1-498a-937c-147f5b924f5f)

You can see that no menu is drawn, any menu previously drawn was hidden with `menu:Visible(false)`

Any help is greatly appreciated and thank you for all the work you've put into this API 🙏

**Comment by manups4e** [comment]
Weird 🤔 could be Lua arrays not starting from 0.. it's an edge case I've never encountered before

**Comment by IsmaelJab** [comment]
Thank you for your quick response, in an effort to debug this I've added a little print statement in the `:Visible` method in ScaleformUI_Lua, notice how the breadcrumbs count does not drop back to 0 after the menu closes

![image](https://github.com/user-attachments/assets/4b839bcd-35e8-4bdd-a1a1-c92be0cc59c5)

Hope it helps

**Comment by manups4e** [comment]
Absolutely barbaric!! I'll dig into this!! 🤔😡

**Comment by IsmaelJab** [comment]
I have made a small client repro command as follows :

```
local function CreateTestMenu()
	if MenuHandler:IsAnyMenuOpen() then print('A menu is already open !') return end
	local menu = UIMenu.New('Menu', 'This is a menu')
	local dummyButton = UIMenuItem.New('Example', 'Example')
	menu:AddItem(dummyButton)
	-- If player exits menu with backspace key, it will reopen normally next time
	-- If player presses the button, the menu will not reopen as it fails the first check
	dummyButton.Activated = function(menu, index)
		print('Menu is now not visible')
		menu:Visible(false)
		-- If we add a MenuHandler:CloseAndClearHistory() here, it starts working again
	end
	menu:Visible(true)
end

RegisterCommand('menu', function(source, args)
	CreateTestMenu()
end, false)
```

I am not sure if we are supposed to use `MenuHandler:CloseAndClearHistory()` as a way to close the current menu everytime though

**Comment by manups4e** [comment]
Absolutely yes! It is made to close everything and reset breadcrumbs handler history

**Comment by IsmaelJab** [comment]
Alright thank you for the clarification ! I guess I got confused because the example menu did not have it so I assumed it was maybe an internal function I was not supposed to use

Have a good day 🙏

**Comment by manups4e** [comment]
Consider that.. that function is made to close menu in cases where is not player request to close it.. normally menu is closed when player closes it via backspace/esc
