### ISSUE TITLE
Header not displayed correctly

### ISSUE THREAD

**Issue by Slyker** [manups4e/ScaleformUI#219]
Hi, as mentionned on discord i'm experiencing issues with header/banner size.
![{AD9C668B-23B2-4688-870C-7F2C2DD89971}](https://github.com/user-attachments/assets/3c3209b3-5e90-4a0f-a9da-8dbaac7587dc)
As you can see on the screenshot the subtitle area overlap on the banner.
I tried with different resolutions but i have a wide screen maybe it's related ???
I made a pretty simple repro here (press F1):
```C#
using CitizenFX.Core;
using ScaleformUI.Menu;
using static CitizenFX.Core.Native.API;

namespace sCoreV1.Client.ScaleformUI___Showcase
{
    internal class HeaderBug : BaseScript
    {
        UIMenu myMenu = new("", "", new(20, 20), customBanner: new("shopui_title_supermod", "shopui_title_supermod"));
        public HeaderBug() {
            myMenu.AddItem(new UIMenuItem("Hello"));
            Tick += async () =>
            {
                if (IsControlJustPressed(0, (int)Control.ReplayStartStopRecording))
                {
                    myMenu.Visible = true;
                }
            };
        }
    }
}
```

**Comment by manups4e** [comment]
![image](https://github.com/user-attachments/assets/16de349e-f6e6-4184-8420-bb58b5fae1b0)

fixed in next update :)

**Comment by manups4e** [comment]
![image](https://github.com/user-attachments/assets/9b7bf359-2e93-49af-9ad1-740e3e5dfc3d)

ok fixed finally and will be ready next update.
