### ISSUE TITLE
Instructional Buttons

### ISSUE THREAD

**Issue by madmetalsat** [manups4e/ScaleformUI#22]
whenever the menu is executed, if it has instructional buttons, after closing, some thread, probably the instructional buttons handle, in memory, keep running, increasing the script tick time.

I believe it has a direct relationship with the buttons, because when I remove all references and create a menu without them, after closing it, the ms returns to the previous idle value.

How to reproduce:
run resmon before opening a menu, it could be example menu, pay attention to the ms time, open and close the menu a few times and compare with previous resmon value

**Comment by manups4e** [comment]
I will investigate this 🤔 can u please tell what ScRt is it? Lua or C#?

**Comment by madmetalsat** [comment]
ow sorry, lua.
Thax man, im using your api for everything in my project, really appreciate your work

**Comment by manups4e** [comment]
https://user-images.githubusercontent.com/4005518/171112788-b56883f8-c649-45e6-9bd5-9e8ecbaac45a.mp4

I can't reproduce your issue.. as you can see my cpu time goes back to 0.13 every time i close the menu.
Also.. the InstructionalButtons thread runs **always**, from the moment you start ScaleformuUI to the moment you stop it.
It simply returns when no button are enabled.
![image](https://user-images.githubusercontent.com/4005518/171113141-84ed5152-a67e-42c1-b9d3-50bec5ec0c0c.png)
