### ISSUE TITLE
Attempt to call a number value (method 'Percentage')

### ISSUE THREAD

**Issue by dev-drozd** [manups4e/ScaleformUI#224]
UIMenuPercentagePanel:Percentage not working when trying to set percentage, gives error:
Attempt to call a number value (method ‘Percentage’)

Use ScaleformUI Version: v5.3.5

Code example:
`
RegisterCommand("getBug2", function(source, args)

	MenuHandler:CloseAndClearHistory()
	
	local Menu = UIMenu.New("Bug test", "Items", 10, 50, false, "commonmenu", "interaction_bgd")
	
	local Item = UIMenuListItem.New("Test item", {"One","Two", "Three"}, 0)
	
	local PercentagePanel = UIMenuPercentagePanel.New("Test", "0%", "100%", 50)
	
	Item.OnListChanged = function(menu, item, index)
		PercentagePanel:Percentage(math.random(0,100)) -- Attempt to call a number value (method 'Percentage')
	end

	Item:AddPanel(PercentagePanel)
   
	Menu:AddItem(Item)
	
	Menu:Visible(true)
	
end, false)
`

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/61a50598cfff417ebe1457629b61e81785bb0f29
