### ISSUE TITLE
UIMenuColorPanel:CurrentSelection visually in the color panel the color does not become selected

### ISSUE THREAD

**Issue by dev-drozd** [manups4e/ScaleformUI#225]
UIMenuColorPanel:CurrentSelection visually in the color panel the color does not become selected

Use ScaleformUI Version: v5.3.5

Code example:

`RegisterCommand("getBug3", function(source, args)

	MenuHandler:CloseAndClearHistory()
	
	local Menu = UIMenu.New("Bug test", "Items", 10, 50, false, "commonmenu", "interaction_bgd")
	
	local Item = UIMenuItem.New("Get random color", "Test description")
	
	local ColorPanel = UIMenuColorPanel.New("Color", 0, 1)
	
	Item.Activated = function()
		local Color = math.random(1,64)
		ColorPanel:CurrentSelection(Color) -- Visual not become selected
		ScaleformUI.Notifications:ShowSubtitle("Color: "..Color, 500)
	end

	Item:AddPanel(ColorPanel)
   
	Menu:AddItem(Item)
	
	Menu:Visible(true)
	
end, false)`

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/61a50598cfff417ebe1457629b61e81785bb0f29
