### ISSUE TITLE
PlayerStatsPanel not added as column.

### ISSUE THREAD

**Issue by chaixshot** [manups4e/ScaleformUI#230]
```lua
local panel = PlayerStatsPanel.New("H@mer", SColor.FromHudColor(158))
panel:HasPlane(false)
panel:HasHeli(false)
panel:HasBoat(false)
panel:HasVehicle(false)
panel.RankInfo:RankLevel(false)
panel:AddStat(PlayerStatsPanelStatItem.New("Stamina", 1.0)
panel:AddStat(PlayerStatsPanelStatItem.New("Shooting", 1.0)
panel:AddStat(PlayerStatsPanelStatItem.New("Strength", 1.0)
panel:AddStat(PlayerStatsPanelStatItem.New("Stealth", 1.0)
panel:AddStat(PlayerStatsPanelStatItem.New("Driving", 1.0)
panel:AddStat(PlayerStatsPanelStatItem.New("Flying", 1.0)
panel:AddStat(PlayerStatsPanelStatItem.New("Mental State", 1.0)
friend:AddPanel(panel)
```
Expect:
![image](https://github.com/user-attachments/assets/879e276f-b54f-49e0-b7c6-dd8a3abb4c10)

Reality:
![image](https://github.com/user-attachments/assets/b6f0c7cb-da61-4643-8e52-5363ab848a27)

**Comment by Mathu-lmn** [comment]
The function header is : `PlayerStatsPanelStatItem.New(label, desc, value)` can you try adding a description ?

**Comment by chaixshot** [comment]
> The function header is : `PlayerStatsPanelStatItem.New(label, desc, value)` can you try adding a description ?

Yes, my default description is "Normal"

**Comment by chaixshot** [comment]
https://github.com/manups4e/ScaleformUI/blob/c845bfab9d6b5436e1683632192d9e6cfaf0c9cd/ScaleformUI_Lua/src/Menus/PauseMenus/LobbyMenu/Items/ItemPanels/PlayerStatsPanel.lua#L162

![image](https://github.com/user-attachments/assets/53587f05-dc21-4698-92c3-bd9bcc7dd897)

I try to fix by this.

**Comment by manups4e** [comment]
🤔 i see.. would you like to make a PR?
