### ISSUE TITLE
Pause menu UIMenuItem color not working.

### ISSUE THREAD

**Issue by chaixshot** [manups4e/ScaleformUI#231]
```lua
text = "Leave Game"
description = "Leave current lobby."
color = 8
highlightColor = 6
textColor = 0
highlightedTextColor = 0
Blink = true
```
https://github.com/manups4e/ScaleformUI/blob/c845bfab9d6b5436e1683632192d9e6cfaf0c9cd/ScaleformUI_Lua/src/Menus/UIMenu/Items/UIMenuItem.lua#L47
**Not work**: color, textColor, highlightedTextColor
**Work**: highlightColor

Hover on **Setting**
![image](https://github.com/user-attachments/assets/bdac78f9-7ad4-4335-b4c8-fb9fa83e6c85)

Hover on **Leave Game**
![image](https://github.com/user-attachments/assets/239fff52-2835-4773-a60d-6ab2b36d204d)

**Comment by manups4e** [comment]
Text color won't work is obsolete as it's handled by text formatting now

**Comment by chaixshot** [comment]
> Text color won't work is obsolete as it's handled by text formatting now

What about default row color?
As i know is 
```
color = Default row color
highlightColor = Row color while hover
textColor = Default text color of row text
highlightedTextColor = Row text color while hover
```

**Comment by chaixshot** [comment]
That mean no adaptive color?

https://github.com/user-attachments/assets/9c02bb74-cad5-471f-b1aa-710f53e3e32e

**Comment by manups4e** [comment]
What do you mean adaptive color?

**Comment by chaixshot** [comment]
I mean row text color on hover and non hover.
I video, Leave Game row useing text format ```"<font color='#c8423b'>Leave Game</font>"```
Because by default text color is white but while hover it will be black that make text easily visible.

**Comment by manups4e** [comment]
you can easily do this using the item.highlighted event and change text color on highlight  true / false.

**Comment by manups4e** [comment]
dynamicity has been removed via textColor and hightlightedTextColor params because if those are used, then text formatting is ignored by the scaleform natural API
