### ISSUE TITLE
SCRIPT ERROR "/example_lobby.lua" or "aattempt to index a nil value (field 'MinimapOverlays')"

### ISSUE THREAD

**Issue by kibus90** [manups4e/ScaleformUI#233]
Hello,

Just installed  ScaleformUI plugin on my server. But I get directly errors. I can't even test it.  Only an additional resource on my server wich I run is "oxmysql" - for the rest it's clear server without any diffrent resources.

Here are errors:
![image](https://github.com/user-attachments/assets/2f0d20ed-e140-4a48-871c-1c03c0082ddf)

I removed from `fxmanifest.lua`:
```
 'example.lua',
    'example_lobby.lua',
    'example_lobby_player.lua',
```

But still I get errors:
![image](https://github.com/user-attachments/assets/c8d91ea8-6d69-4970-a12c-52ce09030c39)

Should I install something additional? Thanks in advance!

**Comment by manups4e** [comment]
you downloaded the github source instead of the release in https://github.com/manups4e/ScaleformUI/releases/tag/v5.3.6

**Comment by manups4e** [comment]
It's dangerous to go alone, take this https://github.com/manups4e/ScaleformUI/wiki/Getting-Started
