### ISSUE TITLE
Menu header CounterPretext

### ISSUE THREAD

**Issue by jtriclin** [manups4e/ScaleformUI#27]
The `CounterPretext` variable is present in the UIMenu script for both CSharp and Lua, but is unusable as of now. 
It might be useful to add support for it to allow updating the color of the counter.

```cs
/// <summary>
/// String to pre-attach to the counter string. Useful for color codes.
/// </summary>
public string CounterPretext { get; set; }
```

**Comment by manups4e** [comment]
what do you mean the color of the counter?

**Comment by jtriclin** [comment]
At the moment, the counter (1/X right of the subtitle) color is blue and cannot be changed. In NativeUI, you were able to change it using the CouterPretext variable. 
In your current version, the variable is still present but is never used.

**Comment by manups4e** [comment]
oh i see.. so you want to change the color right? i'll add a CounterColor variable for that :)

**Comment by manups4e** [comment]
the CounterPretext is not necessary for Scaleforms so i'll remove it..

**Comment by jtriclin** [comment]
Exactly, Thanks !
