### ISSUE TITLE
Multiple Source - Same Target

### ISSUE THREAD

**Issue by tony-stark-17** [manups4e/ScaleformUI#28]
Was building an admin menu using this when I occured an issue that you cant add same menu as many submenus for example an online players options which shows all the onlineplayers as submenus which gets directed to a single menu on click which has the options

**Comment by manups4e** [comment]
yes.. you cannot add more than once the same submenu

**Comment by tony-stark-17** [comment]
I did a workaround right after this issue. Idk maybe the brain was waiting for somethin
`ply.Activated = function (menu,item)
                        if onlineplayers_each.ParentItem and onlineplayers_each.ParentItem ~= ply then
                            onlineplayers:ReleaseMenuFromItem(onlineplayers_each.ParentItem)
                            onlineplayers:BindMenuToItem(onlineplayers_each,ply)
                        else
                            onlineplayers:BindMenuToItem(onlineplayers_each,ply)
                        end
                        print(menu.Extras.id)
                        onlineplayers_each.Title = menu.Extras.name
                        selectedPlayer = menu.Extras.id
                    end`

**Comment by tony-stark-17** [comment]
Great work btw

**Comment by tony-stark-17** [comment]
Any way we can change the subtitle color of the menu

**Comment by manups4e** [comment]
> I did a workaround right after this issue. Idk maybe the brain was waiting for somethin ![image](https://user-images.githubusercontent.com/76168122/176242400-258841b2-0f24-4fd7-bb3f-ccf1b1c66248.png)

regarding this.. you should be able to add the same submenu as long as the menu title is unique for each iteration

**Comment by tony-stark-17** [comment]
> > I did a workaround right after this issue. Idk maybe the brain was waiting for somethin ![image](https://user-images.githubusercontent.com/76168122/176242400-258841b2-0f24-4fd7-bb3f-ccf1b1c66248.png)
> 
> regarding this.. you should be able to add the same submenu as long as the menu title is unique for each iteration

The title was the playername so it was unique

**Comment by Local9** [comment]
Don't know if this has been corrected, but I would believe the title needs to be set before the child menu (submenu) is binded to the parent menu.

**Comment by Local9** [comment]
Seeing more code would help as the current screen shot doesn't show a unique menu as the `onlineplayers_each` isn't deep copied and could be using the same reference.
