### ISSUE TITLE
UIMenuGridPanel and UIMenuPercentagePanel "Changed" events being triggered various times on mouse click.

### ISSUE THREAD

**Issue by madmetalsat** [manups4e/ScaleformUI#31]
I'm sorry to bother you again but I couldn't solve this by myself.

UIMenuGridPanel and UIMenuPercentagePanel change event is being triggered multiple times on mouse click.

video:
https://streamable.com/7mpbn1
simpleMenu .lua file used in the video
[simpleMenu.zip](https://github.com/manups4e/ScaleformUI/files/9274402/simpleMenu.zip)

Tested only in lua with the latest release files + assets

**Comment by manups4e** [comment]
This is their normal behaviour as the code is handled onControlPressed and not JustPressed

**Comment by Local9** [comment]
This should be closed, as this is normal behavour so the user sees information is updated during interaction with the panel, i.e. facial features changing in character creation
