### ISSUE TITLE
Support for adding GtaO style Rank HUD

### ISSUE THREAD

**Issue by EltsuDEV** [manups4e/ScaleformUI#38]
Sorry, but this is only way to get this message to the awesome creation team, THIS IS NOT AN ISSUE, this is suggestion!!

Support for adding Gta V online styled rank/rank up hud, screenshot below:

![image](https://user-images.githubusercontent.com/36920086/201642475-d4debf90-f84b-4f25-a375-0842b32a400d.png)

This would be awesome adding if it is possible to do. Btw this is awesome project, it saved my project i love you : ))))!!!!!!!
And i am sorry, THIS IS NOT AN ISSUE!!

**Comment by manups4e** [comment]
sure i'll make something out of it 👍

**Comment by EltsuDEV** [comment]
Thank you!

**Comment by Local9** [comment]
I'll work on this as its something I did a while back in an old project and I've been wanting to revisit Hud Components;

![image](https://user-images.githubusercontent.com/6077794/206822408-bd303f3a-8051-46bb-9a43-89378760cb1a.png)

**Comment by Local9** [comment]
#42 merged
