### ISSUE TITLE
Error when displaying bigmessageinstance

### ISSUE THREAD

**Issue by fimesfi** [manups4e/ScaleformUI#39]
![image](https://user-images.githubusercontent.com/115319031/201675931-1e715dd2-2e59-43a2-b68c-dcba8838a653.png)
![image](https://user-images.githubusercontent.com/115319031/201675947-bbc430f4-29ed-40c5-a36f-3c919226b688.png)

Hey!! I need some help... What is wrong?

**Comment by manups4e** [comment]
The error seems internal to ScaleformUI I'll fix it later today when I get home.

**Comment by fimesfi** [comment]
Thanks lot!

**Comment by fimesfi** [comment]
Thank you, for fast helping!
