### ISSUE TITLE
Changing PlayerListScoreboard location?

### ISSUE THREAD

**Issue by fimesfi** [manups4e/ScaleformUI#40]
Is it even possible to change ScaleformUI.Scaleforms.PlayerListScoreboard location on screen, like u can do with the menu.

![image](https://user-images.githubusercontent.com/115319031/202437167-fffeb8e1-252d-41fa-92e6-7e6e7621c903.png)
It wont really be able to look at from that position lmao.

**Comment by manups4e** [comment]
Not at this moment, but you can change chat position

**Comment by fimesfi** [comment]
Okay, another question:

How do i easily clear whole PlayerListScoreboard list? So when every time you open it then script removes all rows and then add them again based which players are in server?

**Comment by EltsuDEV** [comment]
> Okay, another question:
> 
> How do i easily clear whole PlayerListScoreboard list? So when every time you open it then script removes all rows and then add them again based which players are in server?

I did not found any solution to this yet : ( pls help me people : D

**Comment by Local9** [comment]
> Okay, another question:
> 
> How do i easily clear whole PlayerListScoreboard list? So when every time you open it then script removes all rows and then add them again based which players are in server?

> > Okay, another question:
> > How do i easily clear whole PlayerListScoreboard list? So when every time you open it then script removes all rows and then add them again based which players are in server?
> 
> I did not found any solution to this yet : (

You can RemoveRow or just clear the PlayerRows and then re-add all players you need to it
