### ISSUE TITLE
Wiki improvements

### ISSUE THREAD

**Issue by EltsuDEV** [manups4e/ScaleformUI#41]
Wiki contains already lots of functions, but there are still some hidden features that you cannot find direct solution. So i'm requesting some wiki improvements, when creators have time. This will also reduce the amount of issues!

**Comment by Local9** [comment]
Do you have anything that can be focused on as this will help in identifying what should be getting the most attention.

**Comment by Local9** [comment]
Wiki has been opened up to public editing, this should help with improving the documentation.
