### ISSUE TITLE
Lobby menu PlayerStatsPanelStatItem issue

### ISSUE THREAD

**Issue by chaixshot** [manups4e/ScaleformUI#53]
This from example.lua
![image](https://user-images.githubusercontent.com/13221018/209914345-92735533-8f1b-4d26-b9e4-0cc19afb72cf.png)

**Comment by manups4e** [comment]
yeah sometimes fricking Adobe Flash CS6 fucks with labels height on saving or on publishing.. dunno why..

**Comment by manups4e** [comment]
![image](https://user-images.githubusercontent.com/4005518/209920680-c2352b02-f646-43ef-8fd6-124dc4a947aa.png)
see?

**Comment by chaixshot** [comment]
This same scale?
![Screenshot (22)](https://user-images.githubusercontent.com/13221018/209920948-148d2816-9410-462f-85d7-782a02dc6637.png)
![Screenshot (23)](https://user-images.githubusercontent.com/13221018/209920940-afa920c4-bfb0-44d3-beb3-bbdec60cb26c.png)

**Comment by manups4e** [comment]
Yup as you can see sometimes flash does stupid things.. pause menu and lobby menu are 2 different gfx so they have different items in them.. anyway I'm releasing a new update right now

**Comment by manups4e** [comment]
fixed in latest release. https://github.com/manups4e/ScaleformUI/releases/tag/2.9
