### ISSUE TITLE
LobbyMenu UIMenuItem RightLabel not work.

### ISSUE THREAD

**Issue by chaixshot** [manups4e/ScaleformUI#62]
https://github.com/manups4e/ScaleformUI/blob/master/ScaleformUI_Lua/src/LobbyMenu/MainView.lua#L190

**Comment by Local9** [comment]
Looked into it, can see where it issue is, will update shortly.

**Comment by Local9** [comment]
Guess there was a reason for it originally and then it was changed but some areas were not updated.

**Comment by chaixshot** [comment]
Still not work.
![image](https://user-images.githubusercontent.com/13221018/210184574-69f21944-721d-4ee0-bdf9-4d42fbf6e902.png)

**Comment by Local9** [comment]
I'm currently looking into the scaleforms code itself.

**Comment by Local9** [comment]
Updates will be found on the PR.

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/c8abde9517c0e36d1b58a2fec5181d08e9ccb570
