### ISSUE TITLE
[MissionDetailsItem] Description overflows background or is too small to read

### ISSUE THREAD

**Issue by Local9** [manups4e/ScaleformUI#75]
Examples;
![image](https://user-images.githubusercontent.com/6077794/214198323-6aedea21-0125-4c05-b34c-29b6fe98a9b9.png)
![image](https://user-images.githubusercontent.com/6077794/214198364-f51a7ae0-5b21-498b-96da-091f232b2694.png)

**Comment by manups4e** [comment]
fixed in https://github.com/manups4e/ScaleformUI/commit/69849a5d171638af444bc2ee957c6c4d2e1152b1
