### ISSUE TITLE
[UIMenuItem] Enable font to be changed on Right Label

### ISSUE THREAD

**Issue by Local9** [manups4e/ScaleformUI#76]
Example from GTA:O Menu, Rockstars name shows in a different font.

![image](https://user-images.githubusercontent.com/6077794/214199815-ff2c4fbb-1e5c-4229-bf9d-3202333aa768.png)

**Comment by Local9** [comment]
Incorrectly mentioned in the PR

**Comment by manups4e** [comment]
this should be made via <C> TEXT </C> tags 🤔 iirc but i'll take a look asap

**Comment by Local9** [comment]
Tested this in the `UIMenuFreemodeDetailsItem` and saw no change to the font.

**Comment by manups4e** [comment]
taken from R* scaleforms 
```
    static function parseHTMLForFonts(str, stdPtSize)
    {
        str = str.split("<C>").join("<FONT FACE=\'" + com.rockstargames.gtav.utils.GTAVUIConfig.CONDENSED_FONT + "\' SIZE=\'" + (stdPtSize + 3) + "\'>");
        str = str.split("</C>").join("<FONT FACE=\'" + com.rockstargames.gtav.utils.GTAVUIConfig.DEFAULT_FONT + "\' SIZE=\'" + stdPtSize + "\'>");
        return str;
    }
```

**Comment by Local9** [comment]
Recommend testing it, as I saw no change in Left or Right labels.

**Comment by manups4e** [comment]
integrated in next major version! https://github.com/manups4e/ScaleformUI/commit/758a0fcf829e756aca616e55849080d9c68b7e07
