### ISSUE TITLE
Menu makes game freeze when populated with 70+ items

### ISSUE THREAD

**Issue by madmetalsat** [manups4e/ScaleformUI#9]
I'm not sure if it's just my problem but when I populate a menu with 100 items (a car shop) it freezes the game for a few seconds before opening. This freeze starts from 70 items and only increases from there. Is there anything I could be doing wrong?

How to replicate:

Just create a main menu and add 70 or more items (UIMenuItem.New)

running in Lua btw

**Comment by manups4e** [comment]
That's more than normal as the menu has to iterate with too many items at once. I'd suggest you to make submenus to group the vehicles into smaller groups
