### ISSUE TITLE
[bug] Lua port current issues...

### ISSUE THREAD

**Issue by ali-exacute** [manups4e/ScaleformUI#98]
- [x] Changing description with `Description` method doesn't work as intended

- [x] Changing Checkbox state while already in menu needs to be duplicated to work correctly

- [x] `CloseAllMenus` function doesn't work and will cause overwrite or duplicates on last opened menu when you open a new menu (needs testing) fixed thanks to @QuadrupleTurbo 

- [ ] building Async is currently kinda useless as it could take a lot of time (2sec) to build up a ~50 item menu with some animations , possibly make it moveable to next index but not to last index untill its built ( tldr : while building can go down , but cant go up past # 1 index) _(Also need a way to fix the animation glitch that this introduce)_

- [x] if current menu is on MaxItemsOnScreen number (like 8), if you go to a new menu and back out , item selection will disappear 

- [x] add missing BigFeedHandler as in C# library

- [x] fix statistics panel not updating values

- [x] when cursor is active `OnItemSelect` is fired for items the cursor is not over the item https://github.com/manups4e/ScaleformUI/commit/a8fee815b47d71401eb0eb1d7932bd7e84a50f8f

_Let me know if i missed anything_

**Comment by manups4e** [comment]
Just to update, there has been some development work on changing how menus are handled. Most updates are mentioned on the [Discord](https://discord.gg/fivemscripters)
Especially for high numbers of items in menus

**Comment by manups4e** [comment]
everything is integrated and fixed in next major version! https://github.com/manups4e/ScaleformUI/commit/758a0fcf829e756aca616e55849080d9c68b7e07
